### ISSUE TITLE
The published npm package does not contain compiled code?

### ISSUE THREAD

**Issue by jdneo** [jumattos/lsif-util#21]
I'm trying the published npm package but got this error:

```
Error: Cannot find module '../lib/main.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\sheche\AppData\Roaming\npm\node_modules\lsif-util\bin\lsif-util:2:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Seems related to these lines: https://github.com/jumattos/lsif-util/blob/master/package.json#L48-L50, `lib/` is not included in the package.

Would you mind to take a look? @jumattos

**Comment by jumattos** [comment]
Ops! You are definitely right, I forgot to include "lib" in the package. I just released a new version fixing the mistake. Sorry!
